#!/usr/bin/env sh

#
# © 2021 Thoughtworks, Inc.
#

echo REACT_APP_PREVIOUS_YEAR_OF_USAGE=$REACT_APP_PREVIOUS_YEAR_OF_USAGE >> .env
echo REACT_APP_DATE_RANGE_VALUE=$REACT_APP_DATE_RANGE_VALUE >> .env
echo REACT_APP_DATE_RANGE_TYPE=$REACT_APP_DATE_RANGE_TYPE >> .env
