runs:
  using: "composite"
  steps:
    # Cache every node_modules folder inside the monorepo
    - name: cache all node_modules
      id: cache-modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        # We use both yarn.lock and package.json as cache keys to ensure that changes to local monorepo packages bust the cache.
        key: ${{ runner.os }}-v${{ matrix.node-version }}-node_modules-${{ hashFiles('yarn.lock', '**/package.json') }}
    - name: find location of global yarn cache
      id: yarn-cache
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: cache global yarn cache
      uses: actions/cache@v2
      if: steps.cache-modules.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: yarn install
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: yarn install --immutable
