language: node_js
node_js:
  - stable
script:
  - npm run bootstrap
  - npm run lint
  - npm test
cache:
  directories:
    - client/node_modules
    - server/node_modules
branches:
  only:
    - trunk
