version: '3.9'

services:
  client:
    image: cloudcarbonfootprint/client:latest
    ports:
      - '8001:80'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
  api:
    image: docker.io/cloudcarbonfootprint/api:latest
    ports:
      - '4000:4000'
    secrets:
      - AZURE_CLIENT_ID
      - AZURE_CLIENT_SECRET
      - AZURE_TENANT_ID
    environment:
      - GCP_USE_BILLING_DATA=false
      - AWS_USE_BILLING_DATA=false
      - AZURE_USE_BILLING_DATA=true
      - AZURE_CLIENT_ID=/run/secrets/AZURE_CLIENT_ID
      - AZURE_CLIENT_SECRET=/run/secrets/AZURE_CLIENT_SECRET
      - AZURE_TENANT_ID=/run/secrets/AZURE_TENANT_ID

secrets:
  AZURE_CLIENT_ID:
    file: ~/.docker/secrets/AZURE_CLIENT_ID
  AZURE_CLIENT_SECRET:
    file: ~/.docker/secrets/AZURE_CLIENT_SECRET
  AZURE_TENANT_ID:
    file: ~/.docker/secrets/AZURE_TENANT_ID
