version: '3.9'

services:
  client:
    build: packages/client
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
  api:
    build: 
      context: packages/
      dockerfile: api/Dockerfile.local
    ports:
      - '4000:4000'
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials
      - $HOME/.config/gcloud/legacy_credentials/cloud-carbon-footprint@appspot.gserviceaccount.com/adc.json:/root/.config/gcloud/service-account-keys.json
    env_file:
      - packages/api/.env
