Parameters:
  AuthorizedRole:
    Description: The trusted entity's ARN that can assume the CCF role
    Type: String
    Default: arn:aws:iam::<ACCOUNT ID>:<NAME>
  BillingDataBucket:
    Description: The S3 bucket where the CUR data lives
    Type: String
    Default: arn:aws:s3:::<YOUR BUCKET NAME>
  QueryResultsBucket:
    Description: The S3 bucket where Athena query results will be stored
    Type: String
    Default: arn:aws:s3:::<YOUR BUCKET NAME>
Resources:
  CCFAthenaRole:
    Type: 'AWS::IAM::Role'
    Description: This role allows Cloud Carbon Footprint application to read Cost and Usage Reports via AWS Athena
    Properties:
      RoleName: 'ccf-athena'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref AuthorizedRole
            Action: sts:AssumeRole
      Policies:
        - PolicyName: athena
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - athena:StartQueryExecution
                  - athena:GetQueryExecution
                  - athena:GetQueryResults
                  - athena:GetWorkGroup
                Resource: '*'
        - PolicyName: glue
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - glue:GetDatabase
                  - glue:GetTable
                  - glue:GetPartitions
                Resource: '*'
        - PolicyName: s3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:ListMultipartUploadParts
                  - s3:AbortMultipartUpload
                  - s3:PutObject
                Resource:
                  - !Ref BillingDataBucket
                  - !Join [ "", [ !Ref BillingDataBucket, "/*"] ]
                  - !Ref QueryResultsBucket
                  - !Join [ "", [ !Ref QueryResultsBucket, "/*"] ]
        - PolicyName: ce
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ce:GetRightsizingRecommendation
                Resource: '*'