version: 2.1
jobs:
  build:
    working_directory: ~/cloud-carbon-footprint
    docker:
      - image: circleci/node:current
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "client/package-lock.json" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "server/package-lock.json" }}
      - run:
          name: setup
          command: 'npm run bootstrap'
      - save_cache:
          key: dependency-cache-{{ checksum "client/package-lock.json" }}
          paths:
            - ./client/node_modules
      - save_cache:
          key: dependency-cache-{{ checksum "server/package-lock.json" }}
          paths:
            - ./server/node_modules
      - run:
          name: lint
          command: 'npm run lint'
      - run:
          name: test
          command: 'npm test'
