version: 2.1
jobs:
  build:
    working_directory: ~/cloud-carbon-footprint
    docker:
      - image: circleci/node:current
    # Currently, the cache is commented out since it's slower than installing dependencies every time. Once the
    # dependency list grows and build time increases, we can start using the cache again. Caching takes about ~30s to
    # resolve and use as of this comment.
    steps:
      - checkout
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "package-lock.json" }}-{{ checksum "client/package-lock.json" }}-{{ checksum "server/package-lock.json" }}
      - run:
          name: setup
          command: "[ ! -d node_modules ] && npm run bootstrap || echo NPM packages unchanged. Using cache."
      # - save_cache:
      #     key: dependency-cache-{{ checksum "package-lock.json" }}-{{ checksum "client/package-lock.json" }}-{{ checksum "server/package-lock.json" }}
      #     paths:
      #       - ./node_modules
      #       - ./client/node_modules
      #       - ./server/node_modules
      - run:
          name: lint
          command: 'npm run lint'
      - run:
          name: test
          command: 'npm test'
  publish:
    working_directory: ~/cloud-carbon-footprint
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          environement:
            MAJOR_REVISION: 0
            MINOR_REVISION: 0
            SHORT_GIT_HASH: $(echo $CIRCLE_SHA1 | cut -c -7)
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            docker build client -t gcr.io/cloud-carbon-footprint/client:$MAJOR_REVISION.$MINOR_REVISION.$SHORT_GIT_HASH
            docker push gcr.io/cloud-carbon-footprint/client:$MAJOR_REVISION.$MINOR_REVISION.$SHORT_GIT_HASH
            docker build server -t gcr.io/cloud-carbon-footprint/server:$MAJOR_REVISION.$MINOR_REVISION.$SHORT_GIT_HASH
            docker push gcr.io/cloud-carbon-footprint/server:$MAJOR_REVISION.$MINOR_REVISION.$SHORT_GIT_HASH
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - publish:
          requires:
            - build