#!/usr/bin/env sh

#
# © 2021 Thoughtworks, Inc.
#

echo AWS_PROXY_ACCOUNT_ID=$AWS_PROXY_ACCOUNT_ID >> .env
echo AWS_PROXY_ROLE_NAME=$AWS_PROXY_ROLE_NAME >> .env
echo AWS_ACCOUNTS=$AWS_ACCOUNTS >> .env
echo AWS_TARGET_ACCOUNT_ROLE_NAME=$AWS_TARGET_ACCOUNT_ROLE_NAME >> .env
echo AWS_AUTH_MODE=$AWS_AUTH_MODE >> .env
echo AWS_ATHENA_REGION=$AWS_ATHENA_REGION >> .env
echo AWS_ATHENA_DB_NAME=$AWS_ATHENA_DB_NAME >> .env
echo AWS_ATHENA_DB_TABLE=$AWS_ATHENA_DB_TABLE >> .env
echo AWS_ATHENA_QUERY_RESULT_LOCATION=$AWS_ATHENA_QUERY_RESULT_LOCATION >> .env
echo AWS_BILLING_ACCOUNT_ID=$AWS_BILLING_ACCOUNT_ID >> .env
echo AWS_BILLING_ACCOUNT_NAME=$AWS_BILLING_ACCOUNT_NAME >> .env
echo AWS_USE_BILLING_DATA="true" >> .env
echo GCP_USE_BILLING_DATA="true" >> .env
echo GCP_PROJECTS=$GCP_PROJECTS >> .env
echo GCP_BIG_QUERY_TABLE=$GCP_BIG_QUERY_TABLE >> .env
echo GCP_BILLING_PROJECT_ID=$GCP_BILLING_PROJECT_ID >> .env
echo GCP_BILLING_PROJECT_NAME=$GCP_BILLING_PROJECT_NAME >> .env
echo AZURE_AUTH_MODE=$AZURE_AUTH_MODE >> .env
echo AZURE_CLIENT_ID=$AZURE_CLIENT_ID >> .env
echo AZURE_CLIENT_SECRET=$AZURE_CLIENT_SECRET >> .env
echo AZURE_TENANT_ID=$AZURE_TENANT_ID >> .env
echo AZURE_USE_BILLING_DATA=$AZURE_USE_BILLING_DATA >> .env
echo LOGGING_MODE="GCP" >> .env
echo GENERATE_SOURCEMAP="false" >> .env
echo GROUP_QUERY_RESULTS_BY=$GROUP_QUERY_RESULTS_BY >> .env
echo GCS_CACHE_BUCKET_NAME=$GCS_CACHE_BUCKET_NAME >> .env
echo CACHE_MODE=$CACHE_MODE >> .env