/*
 * © 2021 Thoughtworks, Inc.
 */

import {
  COMPUTE_PROCESSOR_TYPES,
  cascadeLakeSkylake,
  broadwellHaswell,
} from '@cloud-carbon-footprint/core'

export const RDS_INSTANCE_TYPES: { [instanceType: string]: number } = {
  'db.m5.24xlarge': 96,
  'db.m5.16xlarge': 64,
  'db.m5.12xlarge': 48,
  'db.m5.8xlarge': 32,
  'db.m5.4xlarge': 16,
  'db.m5.2xlarge': 8,
  'db.m5.xlarge': 4,
  'db.m5.large': 2,
  'db.m4.16xlarge': 64,
  'db.m4.10xlarge': 40,
  'db.m4.4xlarge': 16,
  'db.m4.2xlarge': 8,
  'db.m4.xlarge': 4,
  'db.m4.large': 2,
  'db.m3.2xlarge': 8,
  'db.m3.xlarge': 4,
  'db.m3.large': 2,
  'db.m3.medium': 1,
  'db.m1.xlarge': 4,
  'db.m1.large': 2,
  'db.m1.medium': 1,
  'db.m1.small': 1,
  'db.z1d.12xlarge': 48,
  'db.z1d.6xlarge': 24,
  'db.z1d.3xlarge': 12,
  'db.z1d.2xlarge': 8,
  'db.z1d.xlarge': 4,
  'db.z1d.large': 2,
  'db.x1e.32xlarge': 128,
  'db.x1e.16xlarge': 64,
  'db.x1e.8xlarge': 32,
  'db.x1e.4xlarge': 16,
  'db.x1e.2xlarge': 8,
  'db.x1e.xlarge': 4,
  'db.x1.32xlarge': 128,
  'db.x1.16xlarge': 64,
  'db.r5.24xlarge': 96,
  'db.r5.16xlarge': 64,
  'db.r5.12xlarge': 48,
  'db.r5.8xlarge': 32,
  'db.r5.4xlarge': 16,
  'db.r5.2xlarge': 8,
  'db.r5.xlarge': 4,
  'db.r5.large': 2,
  'db.r4.16xlarge': 64,
  'db.r4.8xlarge': 32,
  'db.r4.4xlarge': 16,
  'db.r4.2xlarge': 8,
  'db.r4.xlarge': 4,
  'db.r4.large': 2,
  'db.r3.8xlarge': 32,
  'db.r3.4xlarge': 16,
  'db.r3.2xlarge': 8,
  'db.r3.xlarge': 4,
  'db.r3.large': 2,
  'db.m2.4xlarge': 8,
  'db.m2.2xlarge': 4,
  'db.m2.xlarge': 2,
  'db.t3.2xlarge': 8,
  'db.t3.xlarge': 4,
  'db.t3.large': 2,
  'db.t3.medium': 2,
  'db.t3.small': 2,
  'db.t3.micro': 2,
  'db.t2.2xlarge': 8,
  'db.t2.xlarge': 4,
  'db.t2.large': 2,
  'db.t2.medium': 2,
  'db.t2.small': 1,
  'db.t2.micro': 1,
}
export const CACHE_NODE_TYPES: { [nodeType: string]: number } = {
  'cache.t2.micro': 1,
  'cache.t2.small': 1,
  'cache.t2.medium': 2,
  'cache.t3.micro': 2,
  'cache.t3.small': 2,
  'cache.t3.medium': 2,
  'cache.m4.large': 2,
  'cache.m4.xlarge': 4,
  'cache.m4.2xlarge': 8,
  'cache.m4.4xlarge': 16,
  'cache.m4.10xlarge': 40,
  'cache.m5.large': 2,
  'cache.m5.xlarge': 4,
  'cache.m5.2xlarge': 8,
  'cache.m5.4xlarge': 16,
  'cache.m5.12xlarge': 48,
  'cache.m5.24xlarge': 96,
  'cache.r4.large': 2,
  'cache.r4.xlarge': 4,
  'cache.r4.2xlarge': 8,
  'cache.r4.4xlarge': 16,
  'cache.r4.8xlarge': 32,
  'cache.r4.16xlarge': 64,
  'cache.r5.large': 2,
  'cache.r5.xlarge': 4,
  'cache.r5.2xlarge': 8,
  'cache.r5.4xlarge': 16,
  'cache.r5.12xlarge': 48,
  'cache.r5.24xlarge': 96,
}

export const MSK_INSTANCE_TYPES: { [instanceType: string]: number } = {
  'Kafka.t3.small': 2,
  'Kafka.m5.large': 2,
  'Kafka.m5.xlarge': 4,
  'Kafka.m5.2xlarge': 8,
  'Kafka.m5.4xlarge': 16,
  'Kafka.m5.8xlarge': 32,
  'Kafka.m5.12xlarge': 48,
  'Kafka.m5.16xlarge': 64,
  'Kafka.m5.24xlarge': 96,
}

export const REDSHIFT_INSTANCE_TYPES: {
  [instanceFamily: string]: { [instanceSize: string]: number[] } // [vcpus, memory]
} = {
  dc2: {
    large: [2, 15],
    '8xlarge': [32, 244],
  },
  ra3: {
    xlplus: [4, 32],
    '4xlarge': [12, 96],
    '16xlarge': [48, 384],
  },
  dc1: {
    large: [2, 15],
    '8xlarge': [32, 244],
  },
  ds2: {
    xlarge: [4, 31],
    '8xlarge': [36, 244],
  },
}

export const EC2_INSTANCE_TYPES: {
  [instanceFamily: string]: { [instanceSize: string]: number[] } // [vcpus, memory]
} = {
  mac1: {
    metal: [12, 32],
  },
  t4g: {
    nano: [2, 0.5],
    micro: [2, 1],
    small: [2, 2],
    medium: [2, 4],
    large: [2, 8],
    xlarge: [4, 16],
    '2xlarge': [8, 32],
  },
  t3: {
    nano: [2, 0.5],
    micro: [2, 1],
    small: [2, 2],
    medium: [2, 4],
    large: [2, 8],
    xlarge: [4, 16],
    '2xlarge': [8, 32],
  },
  t3a: {
    nano: [2, 0.5],
    micro: [2, 1],
    small: [2, 2],
    medium: [2, 4],
    large: [2, 8],
    xlarge: [4, 16],
    '2xlarge': [8, 32],
  },
  t2: {
    nano: [1, 0.5],
    micro: [1, 1],
    small: [1, 2],
    medium: [2, 4],
    large: [2, 8],
    xlarge: [4, 16],
    '2xlarge': [8, 32],
  },
  m6g: {
    medium: [1, 4],
    large: [2, 8],
    xlarge: [4, 16],
    '2xlarge': [8, 32],
    '4xlarge': [16, 64],
    '8xlarge': [32, 128],
    '12xlarge': [48, 192],
    '16xlarge': [64, 256],
    metal: [64, 256],
  },
  m6gd: {
    medium: [1, 4],
    large: [2, 8],
    xlarge: [4, 16],
    '2xlarge': [8, 32],
    '4xlarge': [16, 64],
    '8xlarge': [32, 128],
    '12xlarge': [48, 192],
    '16xlarge': [64, 256],
    metal: [64, 256],
  },
  m5: {
    large: [2, 8],
    xlarge: [4, 16],
    '2xlarge': [8, 32],
    '4xlarge': [16, 64],
    '8xlarge': [32, 128],
    '12xlarge': [48, 192],
    '16xlarge': [64, 256],
    '24xlarge': [96, 384],
    metal: [96, 384],
  },
  m5d: {
    large: [2, 8],
    xlarge: [4, 16],
    '2xlarge': [8, 32],
    '4xlarge': [16, 64],
    '8xlarge': [32, 128],
    '12xlarge': [48, 192],
    '16xlarge': [64, 256],
    '24xlarge': [96, 384],
    metal: [96, 384],
  },
  m5a: {
    large: [2, 8],
    xlarge: [4, 16],
    '2xlarge': [8, 32],
    '4xlarge': [16, 64],
    '8xlarge': [32, 128],
    '12xlarge': [48, 192],
    '16xlarge': [64, 256],
    '24xlarge': [96, 384],
  },
  m5ad: {
    large: [2, 8],
    xlarge: [4, 16],
    '2xlarge': [8, 32],
    '4xlarge': [16, 64],
    '8xlarge': [32, 128],
    '12xlarge': [48, 192],
    '16xlarge': [64, 256],
    '24xlarge': [96, 384],
  },
  m5n: {
    large: [2, 8],
    xlarge: [4, 16],
    '2xlarge': [8, 32],
    '4xlarge': [16, 64],
    '8xlarge': [32, 128],
    '12xlarge': [48, 192],
    '16xlarge': [64, 256],
    '24xlarge': [96, 384],
  },
  m5dn: {
    large: [2, 8],
    xlarge: [4, 16],
    '2xlarge': [8, 32],
    '4xlarge': [16, 64],
    '8xlarge': [32, 128],
    '12xlarge': [48, 192],
    '16xlarge': [64, 256],
    '24xlarge': [96, 384],
  },
  m5zn: {
    large: [2, 8],
    xlarge: [4, 16],
    '2xlarge': [8, 32],
    '3xlarge': [12, 48],
    '6xlarge': [24, 96],
    '12xlarge': [48, 192],
    metal: [48, 192],
  },
  m4: {
    large: [2, 8],
    xlarge: [4, 16],
    '2xlarge': [8, 32],
    '4xlarge': [16, 64],
    '10xlarge': [40, 160],
    '16xlarge': [64, 256],
  },
  a1: {
    medium: [1, 2],
    large: [2, 4],
    xlarge: [4, 8],
    '2xlarge': [8, 16],
    '4xlarge': [16, 32],
    metal: [16, 32],
  },
  c5: {
    large: [2, 4],
    xlarge: [4, 8],
    '2xlarge': [8, 16],
    '4xlarge': [16, 32],
    '9xlarge': [36, 72],
    '12xlarge': [48, 96],
    '18xlarge': [72, 144],
    '24xlarge': [96, 192],
    metal: [96, 192],
  },
  c5d: {
    large: [2, 4],
    xlarge: [4, 8],
    '2xlarge': [8, 16],
    '4xlarge': [16, 32],
    '9xlarge': [36, 72],
    '12xlarge': [48, 96],
    '18xlarge': [72, 144],
    '24xlarge': [96, 192],
    metal: [96, 192],
  },
  c5n: {
    large: [2, 5.25],
    xlarge: [4, 10.5],
    '2xlarge': [8, 21],
    '4xlarge': [16, 42],
    '9xlarge': [36, 96],
    '18xlarge': [72, 192],
    metal: [72, 192],
  },
  c5a: {
    large: [2, 4],
    xlarge: [4, 8],
    '2xlarge': [8, 16],
    '4xlarge': [16, 32],
    '8xlarge': [32, 64],
    '12xlarge': [48, 96],
    '16xlarge': [64, 128],
    '24xlarge': [96, 192],
  },
  c5ad: {
    large: [2, 4],
    xlarge: [4, 8],
    '2xlarge': [8, 16],
    '4xlarge': [16, 32],
    '8xlarge': [32, 64],
    '12xlarge': [48, 96],
    '16xlarge': [64, 128],
    '24xlarge': [96, 192],
  },
  c4: {
    large: [2, 3.75],
    xlarge: [4, 7.5],
    '2xlarge': [8, 15],
    '4xlarge': [16, 30],
    '8xlarge': [60],
  },
  c6g: {
    medium: [1, 2],
    large: [2, 4],
    xlarge: [4, 8],
    '2xlarge': [8, 16],
    '4xlarge': [16, 32],
    '8xlarge': [32, 64],
    '12xlarge': [48, 96],
    '16xlarge': [64, 128],
    metal: [64, 128],
  },
  c6gd: {
    medium: [1, 2],
    large: [2, 4],
    xlarge: [4, 8],
    '2xlarge': [8, 16],
    '4xlarge': [16, 32],
    '8xlarge': [32, 64],
    '12xlarge': [48, 96],
    '16xlarge': [64, 128],
    metal: [64, 128],
  },
  r6g: {
    medium: [1, 8],
    large: [2, 16],
    xlarge: [4, 32],
    '2xlarge': [8, 64],
    '4xlarge': [16, 128],
    '8xlarge': [32, 256],
    '12xlarge': [48, 384],
    '16xlarge': [64, 512],
    metal: [64, 512],
  },
  r6gd: {
    medium: [1, 8],
    large: [2, 16],
    xlarge: [4, 32],
    '2xlarge': [8, 64],
    '4xlarge': [16, 128],
    '8xlarge': [32, 256],
    '12xlarge': [48, 384],
    '16xlarge': [64, 512],
    metal: [64, 512],
  },
  r5: {
    large: [2, 16],
    xlarge: [4, 32],
    '2xlarge': [8, 64],
    '4xlarge': [16, 128],
    '8xlarge': [32, 256],
    '12xlarge': [48, 384],
    '16xlarge': [64, 512],
    '24xlarge': [96, 768],
    metal: [96, 768],
  },
  r5d: {
    large: [2, 16],
    xlarge: [4, 32],
    '2xlarge': [8, 64],
    '4xlarge': [16, 128],
    '8xlarge': [32, 256],
    '12xlarge': [48, 384],
    '16xlarge': [64, 512],
    '24xlarge': [96, 768],
    metal: [96, 768],
  },
  r5a: {
    large: [2, 16],
    xlarge: [4, 32],
    '2xlarge': [8, 64],
    '4xlarge': [16, 128],
    '8xlarge': [32, 256],
    '12xlarge': [48, 384],
    '16xlarge': [64, 512],
    '24xlarge': [96, 768],
  },
  r5ad: {
    large: [2, 16],
    xlarge: [4, 32],
    '2xlarge': [8, 64],
    '4xlarge': [16, 128],
    '8xlarge': [32, 256],
    '12xlarge': [48, 384],
    '16xlarge': [64, 512],
    '24xlarge': [96, 768],
  },
  r5n: {
    large: [2, 16],
    xlarge: [4, 32],
    '2xlarge': [8, 64],
    '4xlarge': [16, 128],
    '8xlarge': [32, 256],
    '12xlarge': [48, 384],
    '16xlarge': [64, 512],
    '24xlarge': [96, 768],
  },
  r5dn: {
    large: [2, 16],
    xlarge: [4, 32],
    '2xlarge': [8, 64],
    '4xlarge': [16, 128],
    '8xlarge': [32, 256],
    '12xlarge': [48, 384],
    '16xlarge': [64, 512],
    '24xlarge': [96, 768],
  },
  r4: {
    large: [2, 15.25],
    xlarge: [4, 30.5],
    '2xlarge': [8, 61],
    '4xlarge': [16, 122],
    '8xlarge': [32, 244],
    '16xlarge': [64, 488],
  },
  x1e: {
    xlarge: [4, 122],
    '2xlarge': [8, 244],
    '4xlarge': [16, 488],
    '8xlarge': [32, 976],
    '16xlarge': [64, 1952],
    '32xlarge': [128, 3904],
  },
  x1: {
    '16xlarge': [976],
    '32xlarge': [1952],
  },
  z1d: {
    large: [2, 16],
    xlarge: [4, 32],
    '2xlarge': [8, 64],
    '3xlarge': [12, 96],
    '6xlarge': [24, 192],
    '12xlarge': [48, 384],
    metal: [48, 384],
  },
  r5b: {
    large: [2, 16],
    xlarge: [4, 32],
    '2xlarge': [8, 64],
    '4xlarge': [16, 128],
    '8xlarge': [32, 256],
    '12xlarge': [48, 384],
    '16xlarge': [64, 512],
    '24xlarge': [96, 768],
    metal: [96, 768],
  },
  // // previous generation
  m1: {
    small: [1, 1.7],
    medium: [1, 3.75],
    large: [2, 7.5],
    xlarge: [4, 15],
  },
  m3: {
    medium: [1, 3.75],
    large: [2, 7.5],
    xlarge: [4, 15],
    '2xlarge': [8, 30],
  },
  c1: {
    medium: [2, 1.7],
    xlarge: [8, 7],
  },
  c2: {
    '8xlarge': [32, 60.5],
  },
  c3: {
    large: [2, 3.75],
    xlarge: [4, 7.5],
    '2xlarge': [8, 15],
    '4xlarge': [16, 30],
    '8xlarge': [32, 60],
  },
  g2: {
    '2xlarge': [8, 15],
    '8xlarge': [32, 60],
  },
  m2: {
    xlarge: [2, 17.1],
    '2xlarge': [4, 34.2],
    '4xlarge': [8, 68.4],
  },
  cr1: {
    '8xlarge': [32, 244],
  },
  r3: {
    large: [2, 15.25],
    xlarge: [4, 30.5],
    '2xlarge': [8, 61],
    '4xlarge': [16, 122],
    '8xlarge': [32, 244],
  },
  i2: {
    xlarge: [4, 30.5],
    '2xlarge': [8, 61],
    '4xlarge': [16, 122],
    '8xlarge': [32, 244],
  },
  i3: {
    large: [2, 15.25],
    xlarge: [4, 30.5],
    '2xlarge': [8, 61],
    '4xlarge': [16, 122],
    '8xlarge': [32, 244],
    '16xlarge': [64, 488],
    metal: [72, 512],
  },
  i3en: {
    large: [2, 16],
    xlarge: [4, 32],
    '2xlarge': [8, 64],
    '3xlarge': [12, 96],
    '6xlarge': [24, 192],
    '12xlarge': [48, 384],
    '24xlarge': [96, 768],
    metal: [96, 768],
  },
  d2: {
    xlarge: [4, 30.5],
    '2xlarge': [8, 61],
    '4xlarge': [16, 122],
    '8xlarge': [36, 244],
  },
  hs1: {
    '8xlarge': [16, 117],
  },
  t1: {
    micro: [1, 613],
  },
}

export const BURSTABLE_INSTANCE_BASELINE_UTILIZATION: {
  [instanceType: string]: number
} = {
  't2.nano': 5,
  't2.micro': 10,
  't2.small': 20,
  't2.medium': 20,
  't2.large': 30,
  't2.xlarge': 22.5,
  't2.2xlarge': 17,
  't3.nano': 5,
  't3.micro': 10,
  't3.small': 20,
  't3.medium': 20,
  't3.large': 30,
  't3.xlarge': 40,
  't3.2xlarge': 40,
  't3a.nano': 5,
  't3a.micro': 10,
  't3a.small': 20,
  't3a.medium': 20,
  't3a.large': 30,
  't3a.xlarge': 40,
  't3a.2xlarge': 40,
  't4g.nano': 5,
  't4g.micro': 10,
  't4g.small': 20,
  't4g.medium': 20,
  't4g.large': 30,
  't4g.xlarge': 40,
  't4g.2xlarge': 40,
}

export const INSTANCE_TYPE_COMPUTE_PROCESSOR_MAPPING: {
  [instanceType: string]: string[]
} = {
  'mac1.metal': [COMPUTE_PROCESSOR_TYPES.COFFEE_LAKE],
  't4g.nano': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  't4g.micro': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  't4g.small': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  't4g.medium': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  't4g.large': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  't4g.xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  't4g.2xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  't3.nano': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  't3.micro': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  't3.small': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  't3.medium': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  't3.large': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  't3.xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  't3.2xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  't3a.nano': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  't3a.micro': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  't3a.small': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  't3a.medium': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  't3a.large': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  't3a.xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  't3a.2xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  't2.nano': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  't2.micro': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  't2.small': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  't2.medium': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  't2.large': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  't2.xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  't2.2xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm6g.medium': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'm6g.large': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'm6g.xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'm6g.2xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'm6g.4xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'm6g.8xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'm6g.12xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'm6g.16xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'm6g.metal': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'm6gd.medium': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'm6gd.large': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'm6gd.xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'm6gd.2xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'm6gd.4xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'm6gd.8xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'm6gd.12xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'm6gd.16xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'm6gd.metal': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'm5.large': [COMPUTE_PROCESSOR_TYPES.SKYLAKE],
  'm5.xlarge': [COMPUTE_PROCESSOR_TYPES.SKYLAKE],
  'm5.2xlarge': [COMPUTE_PROCESSOR_TYPES.SKYLAKE],
  'm5.4xlarge': [COMPUTE_PROCESSOR_TYPES.SKYLAKE],
  'm5.8xlarge': [COMPUTE_PROCESSOR_TYPES.SKYLAKE],
  'm5.12xlarge': [COMPUTE_PROCESSOR_TYPES.SKYLAKE],
  'm5.16xlarge': [COMPUTE_PROCESSOR_TYPES.SKYLAKE],
  'm5.24xlarge': [COMPUTE_PROCESSOR_TYPES.SKYLAKE],
  'm5.metal': [COMPUTE_PROCESSOR_TYPES.SKYLAKE],
  'm5d.large': [COMPUTE_PROCESSOR_TYPES.SKYLAKE],
  'm5d.xlarge': [COMPUTE_PROCESSOR_TYPES.SKYLAKE],
  'm5d.2xlarge': [COMPUTE_PROCESSOR_TYPES.SKYLAKE],
  'm5d.4xlarge': [COMPUTE_PROCESSOR_TYPES.SKYLAKE],
  'm5d.8xlarge': [COMPUTE_PROCESSOR_TYPES.SKYLAKE],
  'm5d.12xlarge': [COMPUTE_PROCESSOR_TYPES.SKYLAKE],
  'm5d.16xlarge': [COMPUTE_PROCESSOR_TYPES.SKYLAKE],
  'm5d.24xlarge': [COMPUTE_PROCESSOR_TYPES.SKYLAKE],
  'm5d.metal': [COMPUTE_PROCESSOR_TYPES.SKYLAKE],
  'm5a.large': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'm5a.xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'm5a.2xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'm5a.4xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'm5a.8xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'm5a.12xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'm5a.16xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'm5a.24xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'm5ad.large': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'm5ad.xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'm5ad.2xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'm5ad.4xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'm5ad.8xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'm5ad.12xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'm5ad.16xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'm5ad.24xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'm5n.large': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm5n.xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm5n.2xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm5n.4xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm5n.8xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm5n.12xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm5n.16xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm5n.24xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm5dn.large': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm5dn.xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm5dn.2xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm5dn.4xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm5dn.8xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm5dn.12xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm5dn.16xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm5dn.24xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm5zn.large': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm5zn.xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm5zn.2xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm5zn.3xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm5zn.6xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm5zn.12xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm5zn.metal': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'm4.large': broadwellHaswell,
  'm4.xlarge': broadwellHaswell,
  'm4.2xlarge': broadwellHaswell,
  'm4.4xlarge': broadwellHaswell,
  'm4.10xlarge': broadwellHaswell,
  'm4.16xlarge': broadwellHaswell,
  'a1.medium': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON],
  'a1.large': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON],
  'a1.xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON],
  'a1.2xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON],
  'a1.4xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON],
  'a1.metal': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON],
  'c5.large': cascadeLakeSkylake,
  'c5.xlarge': cascadeLakeSkylake,
  'c5.2xlarge': cascadeLakeSkylake,
  'c5.4xlarge': cascadeLakeSkylake,
  'c5.9xlarge': cascadeLakeSkylake,
  'c5.12xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'c5.18xlarge': cascadeLakeSkylake,
  'c5.24xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'c5.metal': cascadeLakeSkylake,
  'c5d.large': cascadeLakeSkylake,
  'c5d.xlarge': cascadeLakeSkylake,
  'c5d.2xlarge': cascadeLakeSkylake,
  'c5d.4xlarge': cascadeLakeSkylake,
  'c5d.9xlarge': cascadeLakeSkylake,
  'c5d.12xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'c5d.18xlarge': cascadeLakeSkylake,
  'c5d.24xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'c5d.metal': cascadeLakeSkylake,
  'c5n.large': cascadeLakeSkylake,
  'c5n.xlarge': cascadeLakeSkylake,
  'c5n.2xlarge': cascadeLakeSkylake,
  'c5n.4xlarge': cascadeLakeSkylake,
  'c5n.9xlarge': cascadeLakeSkylake,
  'c5n.18xlarge': cascadeLakeSkylake,
  'c5n.metal': cascadeLakeSkylake,
  'c5a.large': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN],
  'c5a.xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN],
  'c5a.2xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN],
  'c5a.4xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN],
  'c5a.8xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN],
  'c5a.12xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN],
  'c5a.16xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN],
  'c5a.24xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN],
  'c5ad.large': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN],
  'c5ad.xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN],
  'c5ad.2xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN],
  'c5ad.4xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN],
  'c5ad.8xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN],
  'c5ad.12xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN],
  'c5ad.16xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN],
  'c5ad.24xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN],
  'c4.large': [COMPUTE_PROCESSOR_TYPES.HASWELL],
  'c4.xlarge': [COMPUTE_PROCESSOR_TYPES.HASWELL],
  'c4.2xlarge': [COMPUTE_PROCESSOR_TYPES.HASWELL],
  'c4.4xlarge': [COMPUTE_PROCESSOR_TYPES.HASWELL],
  'c4.8xlarge': [COMPUTE_PROCESSOR_TYPES.HASWELL],
  'c6g.medium': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'c6g.large': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'c6g.xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'c6g.2xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'c6g.4xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'c6g.8xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'c6g.12xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'c6g.16xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'c6g.metal': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'c6gd.medium': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'c6gd.large': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'c6gd.xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'c6gd.2xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'c6gd.4xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'c6gd.8xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'c6gd.12xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'c6gd.16xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'c6gd.metal': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'r6g.medium': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'r6g.large': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'r6g.xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'r6g.2xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'r6g.4xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'r6g.8xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'r6g.12xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'r6g.16xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'r6g.metal': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'r6gd.medium': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'r6gd.large': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'r6gd.xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'r6gd.2xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'r6gd.4xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'r6gd.8xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'r6gd.12xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'r6gd.16xlarge': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'r6gd.metal': [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2],
  'r5.large': cascadeLakeSkylake,
  'r5.xlarge': cascadeLakeSkylake,
  'r5.2xlarge': cascadeLakeSkylake,
  'r5.4xlarge': cascadeLakeSkylake,
  'r5.8xlarge': cascadeLakeSkylake,
  'r5.12xlarge': cascadeLakeSkylake,
  'r5.16xlarge': cascadeLakeSkylake,
  'r5.24xlarge': cascadeLakeSkylake,
  'r5.metal': cascadeLakeSkylake,
  'r5d.large': cascadeLakeSkylake,
  'r5d.xlarge': cascadeLakeSkylake,
  'r5d.2xlarge': cascadeLakeSkylake,
  'r5d.4xlarge': cascadeLakeSkylake,
  'r5d.8xlarge': cascadeLakeSkylake,
  'r5d.12xlarge': cascadeLakeSkylake,
  'r5d.16xlarge': cascadeLakeSkylake,
  'r5d.24xlarge': cascadeLakeSkylake,
  'r5d.metal': cascadeLakeSkylake,
  'r5a.large': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'r5a.xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'r5a.2xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'r5a.4xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'r5a.8xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'r5a.12xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'r5a.16xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'r5a.24xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'r5ad.large': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'r5ad.xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'r5ad.2xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'r5ad.4xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'r5ad.8xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'r5ad.12xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'r5ad.16xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'r5ad.24xlarge': [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN],
  'r5n.large': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5n.xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5n.2xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5n.4xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5n.8xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5n.12xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5n.16xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5n.24xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5dn.large': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5dn.xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5dn.2xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5dn.4xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5dn.8xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5dn.12xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5dn.16xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5dn.24xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r4.large': [COMPUTE_PROCESSOR_TYPES.BROADWELL],
  'r4.xlarge': [COMPUTE_PROCESSOR_TYPES.BROADWELL],
  'r4.2xlarge': [COMPUTE_PROCESSOR_TYPES.BROADWELL],
  'r4.4xlarge': [COMPUTE_PROCESSOR_TYPES.BROADWELL],
  'r4.8xlarge': [COMPUTE_PROCESSOR_TYPES.BROADWELL],
  'r4.16xlarge': [COMPUTE_PROCESSOR_TYPES.BROADWELL],
  'x1e.xlarge': [COMPUTE_PROCESSOR_TYPES.HASWELL],
  'x1e.2xlarge': [COMPUTE_PROCESSOR_TYPES.HASWELL],
  'x1e.4xlarge': [COMPUTE_PROCESSOR_TYPES.HASWELL],
  'x1e.8xlarge': [COMPUTE_PROCESSOR_TYPES.HASWELL],
  'x1e.16xlarge': [COMPUTE_PROCESSOR_TYPES.HASWELL],
  'x1e.32xlarge': [COMPUTE_PROCESSOR_TYPES.HASWELL],
  'x1.16xlarge': [COMPUTE_PROCESSOR_TYPES.HASWELL],
  'x1.32xlarge': [COMPUTE_PROCESSOR_TYPES.HASWELL],
  'z1d.large': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'z1d.xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'z1d.2xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'z1d.3xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'z1d.6xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'z1d.12xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'z1d.metal': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5b.large': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5b.xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5b.2xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5b.4xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5b.8xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5b.12xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5b.16xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5b.24xlarge': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'r5b.metal': [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE],
  'd2.xlarge': [COMPUTE_PROCESSOR_TYPES.HASWELL],
  'd2.2xlarge': [COMPUTE_PROCESSOR_TYPES.HASWELL],
  'd2.4xlarge': [COMPUTE_PROCESSOR_TYPES.HASWELL],
  'd2.8xlarge': [COMPUTE_PROCESSOR_TYPES.HASWELL],
  'm1.small': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'm1.medium': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'm1.large': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'm1.xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'm3.medium': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'm3.large': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'm3.xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'm3.2xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'c1.medium': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'c1.xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'c2.8xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'c3.large': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'c3.xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'c3.2xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'c3.4xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'c3.8xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'g2.2xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'g2.8xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'm2.xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'm2.2xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'm2.4xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'cr1.8xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'r3.large': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'r3.xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'r3.2xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'r3.4xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'r3.8xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'i2.xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'i2.2xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'i2.4xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'i2.8xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'i3.large': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'i3.xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'i3.2xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'i3.4xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'i3.8xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'i3.16xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'i3.metal': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'i3en.large': cascadeLakeSkylake,
  'i3en.xlarge': cascadeLakeSkylake,
  'i3en.2xlarge': cascadeLakeSkylake,
  'i3en.3xlarge': cascadeLakeSkylake,
  'i3en.6xlarge': cascadeLakeSkylake,
  'i3en.12xlarge': cascadeLakeSkylake,
  'i3en.24xlarge': cascadeLakeSkylake,
  'i3en.metal': cascadeLakeSkylake,
  'hs1.8xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  't1.micro': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'dc2.large': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'dc2.8xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'ra3.xlplus': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'ra3.4xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'ra3.16xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'dc1.large': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'dc1.8xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'ds2.xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
  'ds2.8xlarge': [COMPUTE_PROCESSOR_TYPES.UNKNOWN],
}

export const GPU_INSTANCES_TYPES: string[] = [
  'p4d.24xlarge',
  'p3.2xlarge',
  'p3.8xlarge',
  'p3.16xlarge',
  'p3dn.24xlarge',
  'p2.xlarge',
  'p2.8xlarge',
  'p2.16xlarge',
  'nf1.xlarge',
  'inf1.2xlarge',
  'inf1.6xlarge',
  'inf1.24xlarge',
  'g4dn.xlarge',
  'g4dn.2xlarge',
  'g4dn.4xlarge',
  'g4dn.8xlarge',
  'g4dn.16xlarge',
  'g4dn.12xlarge',
  'g4dn.metal',
  'g4ad.xlarge',
  'g4ad.2xlarge',
  'g4ad.4xlarge',
  'g4ad.8xlarge',
  'g4ad.16xlarge',
  'g3s.xlarge',
  'g3.4xlarge',
  'g3.8xlarge',
  'g3.16xlarge',
  'f1.2xlarge',
  'f1.4xlarge',
  'f1.16xlarge',
]
