#!/bin/bash

#
# © 2020 ThoughtWorks, Inc. All rights reserved.
#

echo AWS_PROXY_ACCOUNT_ID=$AWS_PROXY_ACCOUNT_ID >> .env
echo AWS_PROXY_ROLE_NAME=$AWS_PROXY_ROLE_NAME >> .env
echo AWS_ACCOUNTS=$AWS_ACCOUNTS >> .env
echo GCP_PROJECTS=$GCP_PROJECTS >> .env
echo GCP_TARGET_ACCOUNT_EMAIL=$GCP_TARGET_ACCOUNT_EMAIL >> .env
echo GCP_TARGET_ACCOUNT_PRIVATE_KEY=$GCP_TARGET_ACCOUNT_PRIVATE_KEY >> .env
echo LOGGING_MODE="GCP" >> .env
echo GENERATE_SOURCEMAP="false" >> .env
