/*
 * © 2020 ThoughtWorks, Inc. All rights reserved.
 */

export enum COMPUTE_PROCESSOR_TYPES {
  CASCADE_LAKE = 'Cascade Lake',
  SKYLAKE = 'Skylake',
  HASWELL = 'Haswell',
  BROADWELL = 'Broadwell',
  COFFEE_LAKE = 'Coffee lake',
  AMD_EPYC_1ST_GEN = 'AMD EPYC 1st Gen',
  AMD_EPYC_2ND_GEN = 'AMD EPYC 2nd Gen',
  GPU = 'GPU',
  AWS_GRAVITON = 'AWS Graviton',
  AWS_GRAVITON_2 = 'AWS Graviton2',
  UNKNOWN = 'Unknown',
}

export const cascadeLakeSkylake = [
  COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE,
  COMPUTE_PROCESSOR_TYPES.SKYLAKE,
]

export const broadwellHaswell = [
  COMPUTE_PROCESSOR_TYPES.HASWELL,
  COMPUTE_PROCESSOR_TYPES.BROADWELL,
]

export const cascadeLakeSkylakeBroadwellHaswell = [
  COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE,
  COMPUTE_PROCESSOR_TYPES.SKYLAKE,
  COMPUTE_PROCESSOR_TYPES.BROADWELL,
  COMPUTE_PROCESSOR_TYPES.HASWELL,
]

export const cascadeLakeSkylakeBroadwell = [
  COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE,
  COMPUTE_PROCESSOR_TYPES.SKYLAKE,
  COMPUTE_PROCESSOR_TYPES.BROADWELL,
]

export const cascadeLakeHaswell = [
  COMPUTE_PROCESSOR_TYPES.HASWELL,
  COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE,
]
