apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloud-carbon-footprint.fullname" . }}-client
  labels:
    {{- include "cloud-carbon-footprint.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  replicas: {{ .Values.client.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "cloud-carbon-footprint.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: client
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/configmap-api.yaml") . | sha256sum }}
      labels:
        {{- include "cloud-carbon-footprint.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: client
    spec:
      {{- with .Values.client.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cloud-carbon-footprint.fullname" . }}-api
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.client.deployment.image.repository }}:{{ .Values.client.deployment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.client.deployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.client.deployment.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.client.deployment.securityContext | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "cloud-carbon-footprint.fullname" . }}-client
            defaultMode: 0755
      {{- with .Values.api.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.deployment.toleration }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.deployment.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
