{{- if .Values.client.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cloud-carbon-footprint.fullname" . }}-client
  labels:
    {{- include "cloud-carbon-footprint.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  ingressClassName: {{ required "ingressClassName is mandatory, you must set .Values.client.ingress.className" .Values.client.ingress.className }}
  rules:
    {{- range .Values.client.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cloud-carbon-footprint.fullname" $ }}-client
                port:
                  name: {{ $.Values.client.service.port.name }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "cloud-carbon-footprint.fullname" $ }}-api
                port:
                  name: {{ $.Values.api.service.port.name }}
    {{- end }}
  tls:
    {{ .Values.client.ingress.tls | toYaml | nindent 4 }}
{{- end }}
