/*
 * © 2021 Thoughtworks, Inc.
 */

export enum COMPUTE_PROCESSOR_TYPES {
  CASCADE_LAKE = 'Cascade Lake',
  SKYLAKE = 'Skylake',
  HASWELL = 'Haswell',
  BROADWELL = 'Broadwell',
  COFFEE_LAKE = 'Coffee Lake',
  SANDY_BRIDGE = 'Sandy Bridge',
  IVY_BRIDGE = 'Ivy Bridge',
  AMD_EPYC_1ST_GEN = 'AMD EPYC 1st Gen',
  AMD_EPYC_2ND_GEN = 'AMD EPYC 2nd Gen',
  GPU = 'GPU',
  AWS_GRAVITON = 'AWS Graviton',
  AWS_GRAVITON_2 = 'AWS Graviton2',
  UNKNOWN = 'Unknown',
}

export const cascadeLakeSkylake = [
  COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE,
  COMPUTE_PROCESSOR_TYPES.SKYLAKE,
]

export const broadwellHaswell = [
  COMPUTE_PROCESSOR_TYPES.HASWELL,
  COMPUTE_PROCESSOR_TYPES.BROADWELL,
]

export const broadwellSkylake = [
  COMPUTE_PROCESSOR_TYPES.BROADWELL,
  COMPUTE_PROCESSOR_TYPES.SKYLAKE,
]

export const broadwelCascadeLake = [
  COMPUTE_PROCESSOR_TYPES.BROADWELL,
  COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE,
]

export const cascadeLakeSkylakeBroadwellHaswell = [
  COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE,
  COMPUTE_PROCESSOR_TYPES.SKYLAKE,
  COMPUTE_PROCESSOR_TYPES.BROADWELL,
  COMPUTE_PROCESSOR_TYPES.HASWELL,
]

export const cascadeLakeSkylakeBroadwell = [
  COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE,
  COMPUTE_PROCESSOR_TYPES.SKYLAKE,
  COMPUTE_PROCESSOR_TYPES.BROADWELL,
]

export const cascadeLakeHaswell = [
  COMPUTE_PROCESSOR_TYPES.HASWELL,
  COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE,
]

export const skyLakeBroadwellHaswellAMDRome = [
  COMPUTE_PROCESSOR_TYPES.SKYLAKE,
  COMPUTE_PROCESSOR_TYPES.BROADWELL,
  COMPUTE_PROCESSOR_TYPES.HASWELL,
  COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN,
]

export const skyLakeBroadwellHaswellSandyBridgeIvyBridge = [
  COMPUTE_PROCESSOR_TYPES.SKYLAKE,
  COMPUTE_PROCESSOR_TYPES.BROADWELL,
  COMPUTE_PROCESSOR_TYPES.HASWELL,
  COMPUTE_PROCESSOR_TYPES.SANDY_BRIDGE,
  COMPUTE_PROCESSOR_TYPES.IVY_BRIDGE,
]
