/*
 * © 2021 Thoughtworks, Inc.
 */
import {
  getAverage,
  getWattsByAverageOrMedian,
  CloudConstantsByProvider,
  CloudConstantsEmissionsFactors,
  COMPUTE_PROCESSOR_TYPES,
  EstimateUnknownUsageBy,
  US_NERC_REGIONS_EMISSIONS_FACTORS,
} from '@cloud-carbon-footprint/core'

import { AWS_REGIONS } from '../lib/AWSRegions'

export const AWS_CLOUD_CONSTANTS: CloudConstantsByProvider = {
  SSDCOEFFICIENT: 1.2, // watt hours / terabyte hour
  HDDCOEFFICIENT: 0.65, // watt hours / terabyte hour
  MEMORY_AVG: 80.69,
  MEMORY_BY_COMPUTE_PROCESSOR: {
    // gigaBytes / physical chip
    [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE.name]:
      COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE.gb_chip_avg,
    [COMPUTE_PROCESSOR_TYPES.SKYLAKE.name]:
      COMPUTE_PROCESSOR_TYPES.SKYLAKE.gb_chip_avg,
    [COMPUTE_PROCESSOR_TYPES.BROADWELL.name]:
      COMPUTE_PROCESSOR_TYPES.BROADWELL.gb_chip_avg,
    [COMPUTE_PROCESSOR_TYPES.HASWELL.name]:
      COMPUTE_PROCESSOR_TYPES.HASWELL.gb_chip_avg,
    [COMPUTE_PROCESSOR_TYPES.COFFEE_LAKE.name]:
      COMPUTE_PROCESSOR_TYPES.COFFEE_LAKE.gb_chip_avg,
    [COMPUTE_PROCESSOR_TYPES.SANDY_BRIDGE.name]:
      COMPUTE_PROCESSOR_TYPES.SANDY_BRIDGE.gb_chip_avg,
    [COMPUTE_PROCESSOR_TYPES.IVY_BRIDGE.name]:
      COMPUTE_PROCESSOR_TYPES.IVY_BRIDGE.gb_chip_avg,
    [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN.name]:
      COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN.gb_chip_avg,
    [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN.name]:
      COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN.gb_chip_avg,
    [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2.name]:
      COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2.gb_chip_avg,
  },
  getMemory: (computeProcessors: string[]): number => {
    const memoryForProcessors: number[] = computeProcessors.map(
      (processor: string) => {
        return AWS_CLOUD_CONSTANTS.MEMORY_BY_COMPUTE_PROCESSOR[processor]
      },
    )
    const averageMemoryForProcessors = getAverage(memoryForProcessors)
    return averageMemoryForProcessors
      ? averageMemoryForProcessors
      : AWS_CLOUD_CONSTANTS.MEMORY_AVG
  },
  MIN_WATTS_AVG: 0.74,
  MIN_WATTS_BY_COMPUTE_PROCESSOR: {
    // CPUs
    [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE.name]:
      COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE.min_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.SKYLAKE.name]:
      COMPUTE_PROCESSOR_TYPES.SKYLAKE.min_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.BROADWELL.name]:
      COMPUTE_PROCESSOR_TYPES.BROADWELL.min_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.HASWELL.name]:
      COMPUTE_PROCESSOR_TYPES.HASWELL.min_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.COFFEE_LAKE.name]:
      COMPUTE_PROCESSOR_TYPES.COFFEE_LAKE.min_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.SANDY_BRIDGE.name]:
      COMPUTE_PROCESSOR_TYPES.SANDY_BRIDGE.min_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.IVY_BRIDGE.name]:
      COMPUTE_PROCESSOR_TYPES.IVY_BRIDGE.min_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN.name]:
      COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN.min_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN.name]:
      COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN.min_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2.name]:
      COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2.min_watts_avg,
    // GPUs
    [COMPUTE_PROCESSOR_TYPES.NVIDIA_K520.name]:
      COMPUTE_PROCESSOR_TYPES.NVIDIA_K520.min_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.NVIDIA_A10G.name]:
      COMPUTE_PROCESSOR_TYPES.NVIDIA_A10G.min_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.NVIDIA_T4.name]:
      COMPUTE_PROCESSOR_TYPES.NVIDIA_T4.min_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_M60.name]:
      COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_M60.min_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_K80.name]:
      COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_K80.min_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_V100.name]:
      COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_V100.min_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_A100.name]:
      COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_A100.min_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_P4.name]:
      COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_P4.min_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_P100.name]:
      COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_P100.min_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.AMD_RADEON_PRO_V520.name]:
      COMPUTE_PROCESSOR_TYPES.AMD_RADEON_PRO_V520.min_watts_avg,
  },
  getMinWatts: (computeProcessors: string[]): number => {
    const minWattsForProcessors: number[] = computeProcessors.map(
      (processor: string) => {
        return AWS_CLOUD_CONSTANTS.MIN_WATTS_BY_COMPUTE_PROCESSOR[processor]
      },
    )
    const averageWattsForProcessors = getWattsByAverageOrMedian(
      computeProcessors,
      minWattsForProcessors,
    )
    return averageWattsForProcessors
      ? averageWattsForProcessors
      : AWS_CLOUD_CONSTANTS.MIN_WATTS_AVG
  },
  MAX_WATTS_AVG: 3.5,
  MAX_WATTS_BY_COMPUTE_PROCESSOR: {
    // CPUs
    [COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE.name]:
      COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE.max_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.SKYLAKE.name]:
      COMPUTE_PROCESSOR_TYPES.SKYLAKE.max_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.BROADWELL.name]:
      COMPUTE_PROCESSOR_TYPES.BROADWELL.max_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.HASWELL.name]:
      COMPUTE_PROCESSOR_TYPES.HASWELL.max_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.COFFEE_LAKE.name]:
      COMPUTE_PROCESSOR_TYPES.COFFEE_LAKE.max_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.SANDY_BRIDGE.name]:
      COMPUTE_PROCESSOR_TYPES.SANDY_BRIDGE.max_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.IVY_BRIDGE.name]:
      COMPUTE_PROCESSOR_TYPES.IVY_BRIDGE.max_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN.name]:
      COMPUTE_PROCESSOR_TYPES.AMD_EPYC_1ST_GEN.max_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN.name]:
      COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN.max_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2.name]:
      COMPUTE_PROCESSOR_TYPES.AWS_GRAVITON_2.max_watts_avg,
    // GPUs
    [COMPUTE_PROCESSOR_TYPES.NVIDIA_K520.name]:
      COMPUTE_PROCESSOR_TYPES.NVIDIA_K520.max_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.NVIDIA_A10G.name]:
      COMPUTE_PROCESSOR_TYPES.NVIDIA_A10G.max_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.NVIDIA_T4.name]:
      COMPUTE_PROCESSOR_TYPES.NVIDIA_T4.max_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_M60.name]:
      COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_M60.max_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_K80.name]:
      COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_K80.max_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_V100.name]:
      COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_V100.max_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_A100.name]:
      COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_A100.max_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_P4.name]:
      COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_P4.max_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_P100.name]:
      COMPUTE_PROCESSOR_TYPES.NVIDIA_TESLA_P100.max_watts_avg,
    [COMPUTE_PROCESSOR_TYPES.AMD_RADEON_PRO_V520.name]:
      COMPUTE_PROCESSOR_TYPES.AMD_RADEON_PRO_V520.max_watts_avg,
  },
  getMaxWatts: (computeProcessors: string[]): number => {
    const maxWattsForProcessors: number[] = computeProcessors.map(
      (processor: string) => {
        return AWS_CLOUD_CONSTANTS.MAX_WATTS_BY_COMPUTE_PROCESSOR[processor]
      },
    )
    const averageWattsForProcessors = getWattsByAverageOrMedian(
      computeProcessors,
      maxWattsForProcessors,
    )
    return averageWattsForProcessors
      ? averageWattsForProcessors
      : AWS_CLOUD_CONSTANTS.MAX_WATTS_AVG
  },
  NETWORKING_COEFFICIENT: 0.001, // kWh / Gb
  MEMORY_COEFFICIENT: 0.000392, // kWh / Gb
  PUE_AVG: 1.135,
  getPUE: (): number => {
    return AWS_CLOUD_CONSTANTS.PUE_AVG
  },
  AVG_CPU_UTILIZATION_2020: 50,
  REPLICATION_FACTORS: {
    S3: 3,
    S3_ONE_ZONE_REDUCED_REDUNDANCY: 2,
    EC2_EBS_VOLUME: 2,
    EC2_EBS_SNAPSHOT: 3,
    EFS: 3,
    EFS_ONE_ZONE: 2,
    RDS_BACKUP: 3,
    RDS_AURORA: 6,
    RDS_MULTI_AZ: 2,
    DOCUMENT_DB_BACKUP: 3,
    DOCUMENT_DB_STORAGE: 2,
    DYNAMO_DB: 2,
    ECR_STORAGE: 3,
    DOCUMENT_ELASTICACHE_BACKUP: 3,
    SIMPLE_DB: 2,
    DEFAULT: 1,
  },
  KILOWATT_HOURS_BY_SERVICE_AND_USAGE_UNIT: {
    total: {},
  },
  ESTIMATE_UNKNOWN_USAGE_BY: EstimateUnknownUsageBy.COST,
  SERVER_EXPECTED_LIFESPAN: 35040, // 4 years in hours
}

export const AWS_EMISSIONS_FACTORS_METRIC_TON_PER_KWH: CloudConstantsEmissionsFactors =
  {
    [AWS_REGIONS.US_EAST_1]: US_NERC_REGIONS_EMISSIONS_FACTORS.SERC,
    [AWS_REGIONS.US_EAST_2]: US_NERC_REGIONS_EMISSIONS_FACTORS.RFC,
    [AWS_REGIONS.US_WEST_1]: US_NERC_REGIONS_EMISSIONS_FACTORS.WECC,
    [AWS_REGIONS.US_WEST_2]: US_NERC_REGIONS_EMISSIONS_FACTORS.WECC,
    [AWS_REGIONS.US_GOV_EAST_1]: US_NERC_REGIONS_EMISSIONS_FACTORS.SERC,
    [AWS_REGIONS.US_GOV_WEST_1]: US_NERC_REGIONS_EMISSIONS_FACTORS.WECC,
    [AWS_REGIONS.AF_SOUTH_1]: 0.000928,
    [AWS_REGIONS.AP_EAST_1]: 0.00081,
    [AWS_REGIONS.AP_SOUTH_1]: 0.000708,
    [AWS_REGIONS.AP_NORTHEAST_3]: 0.000506,
    [AWS_REGIONS.AP_NORTHEAST_2]: 0.0005,
    [AWS_REGIONS.AP_SOUTHEAST_1]: 0.0004085,
    [AWS_REGIONS.AP_SOUTHEAST_2]: 0.00079,
    [AWS_REGIONS.AP_NORTHEAST_1]: 0.000506,
    [AWS_REGIONS.CA_CENTRAL_1]: 0.00013,
    [AWS_REGIONS.CN_NORTH_1]: 0.000555,
    [AWS_REGIONS.CN_NORTHWEST_1]: 0.000555,
    [AWS_REGIONS.EU_CENTRAL_1]: 0.000338,
    [AWS_REGIONS.EU_WEST_1]: 0.000316,
    [AWS_REGIONS.EU_WEST_2]: 0.000228,
    [AWS_REGIONS.EU_SOUTH_1]: 0.000233,
    [AWS_REGIONS.EU_WEST_3]: 0.000052,
    [AWS_REGIONS.EU_NORTH_1]: 0.000008,
    [AWS_REGIONS.ME_SOUTH_1]: 0.000732,
    [AWS_REGIONS.SA_EAST_1]: 0.000074,
    [AWS_REGIONS.UNKNOWN]: 0.00038738, // Average of the above regions
  }
