/*
 * © 2021 Thoughtworks, Inc.
 */

export enum AWS_RECOMMENDATIONS_TARGETS {
  SAME_INSTANCE_FAMILY = 'SAME_INSTANCE_FAMILY',
  CROSS_INSTANCE_FAMILY = 'CROSS_INSTANCE_FAMILY',
}

export const AWS_DEFAULT_RECOMMENDATION_TARGET =
  AWS_RECOMMENDATIONS_TARGETS.SAME_INSTANCE_FAMILY
