name: Lint & Test
on:
  push:
    branches: [trunk, gh-actions]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14']
    steps:
      - uses: actions/checkout@v2
      - name: setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install packages
        run: yarn install --immutable
      - name: lint
        run: yarn lint
      - name: test
        run: yarn test
