name: PR
on:
  pull_request:
    branches: [trunk]
    types: [opened, synchronize, reopened]
    paths-ignore:
        - 'microsite/**'
        - '.github/workflows/deploy-microsite.yml'
jobs:
  lint-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ignore draft pull requests
        if: github.event.pull_request.draft
        run: exit
      - name: setup node 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: cache node_modules
        id: cache-modules
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          # We use both yarn.lock and package.json as cache keys to ensure that changes to local monorepo packages bust the cache.
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock', '**/package.json') }}
      - name: yarn cache dir
        id: yarn-cache
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - name: cache yarn
        uses: actions/cache@v4
        if: steps.cache-modules.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: yarn install
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn
      - name: lint
        run: yarn lint
      - name: test and upload coverage
        run: yarn test

   